--#####################################################################################################################
--#####################################################################################################################
--Skript for Update of Postgres package ABCD to version 15
--replace "#project#" with Name of the project
--the string at the begin of the line --## is used to mark end and begin of a command
--#####################################################################################################################
--#####################################################################################################################

--#####################################################################################################################
--######   New view public.ABCD_NameBotanical          ################################################################
--#####################################################################################################################

CREATE OR REPLACE VIEW public."ABCD_NameBotanical"
 AS
 SELECT U."ID",
    T."GenusOrSupragenericName" AS "GenusOrMonomial",
    '' AS "FirstEpithet",
    '' AS "InfraspecificEpithet",
    "TaxonomicRank" AS "Rank",
    case when T."TaxonName" like '% x %' then 'x' else NULL end AS "HybridFlag",
    '' AS "AuthorTeamParenthesis",
    substring("TaxonName", LENGTH("TaxonNameSinAuthor") + 2, 255) AS "AuthorTeam"
   FROM "#project#"."ABCD_Unit" U
   JOIN "#project#"."ABCD__Unit_LastIdentification" L ON U."CollectionSpecimenID" = L."CollectionSpecimenID" AND U."IdentificationUnitID" = L."IdentificationUnitID"
   JOIN "#project#"."CacheIdentification" I ON I."CollectionSpecimenID" = L."CollectionSpecimenID" 
   AND I."IdentificationUnitID" = L."IdentificationUnitID" AND I."IdentificationSequence" = L."IdentificationSequence"
   JOIN public."TaxonSynonymy" T ON T."NameURI" = I."NameURI";

COMMENT ON VIEW public."ABCD_NameBotanical"
    IS 'ABCD: ScientificName / NameAtomised / Botanical';

COMMENT ON COLUMN public."ABCD_NameBotanical"."GenusOrMonomial"
    IS 'ABCD: ScientificName/NameAtomised/Botanical/GenusOrMonomial. Derived from GenusOrSupragenericName in DTN.TaxonName';

COMMENT ON COLUMN public."ABCD_NameBotanical"."FirstEpithet"
    IS 'ABCD: ScientificName/NameAtomised/Botanical/FirstEpithet. Derived from SpeciesEpithet in DTN.TaxonName';

COMMENT ON COLUMN public."ABCD_NameBotanical"."InfraspecificEpithet"
    IS 'ABCD: ScientificName/NameAtomised/Botanical/InfraspecificEpithet. Derived from InfraspecificEpithet in DTN.TaxonName';

COMMENT ON COLUMN public."ABCD_NameBotanical"."Rank"
    IS 'ABCD: ScientificName/NameAtomised/Botanical/Rank. Derived from TaxonomicRank in DTN.TaxonName';

COMMENT ON COLUMN public."ABCD_NameBotanical"."HybridFlag"
    IS 'ABCD: ScientificName/NameAtomised/Botanical/HybridFlag. Derived from IsHybrid in DTN.TaxonName';

COMMENT ON COLUMN public."ABCD_NameBotanical"."AuthorTeamParenthesis"
    IS 'ABCD: ScientificName/NameAtomised/Botanical/AuthorTeamParenthesis. Derived from BasionymAuthors in DTN.TaxonName';

COMMENT ON COLUMN public."ABCD_NameBotanical"."AuthorTeam"
    IS 'ABCD: ScientificName/NameAtomised/Botanical/AuthorTeam. Derived from CombiningAuthors in DTN.TaxonName';


--#####################################################################################################################
--######   Fixing the encode_uri function according to Copilot   ######################################################
--######   the previous version taken from https://stackoverflow.com/a/60260190 missed to encode the & sign   #########
--#####################################################################################################################

CREATE OR REPLACE FUNCTION public.encode_uri(
	text)
    RETURNS text
    LANGUAGE 'sql'
    COST 100
    IMMUTABLE STRICT PARALLEL UNSAFE
AS $BODY$

    select string_agg(
        case
            when bytes > 1 or c !~ '[0-9a-zA-Z_.-]+' then 
                regexp_replace(encode(convert_to(c, 'utf-8')::bytea, 'hex'), '(..)', E'%\\1', 'g')
            else 
                c
        end,
        ''
    )
    from (
        select c, octet_length(c) bytes
        from regexp_split_to_table($1, '') c
    ) q;
$BODY$;

ALTER FUNCTION public.encode_uri(text)
    OWNER TO "CacheAdmin";

GRANT EXECUTE ON FUNCTION public.encode_uri(text) TO "CacheAdmin";

GRANT EXECUTE ON FUNCTION public.encode_uri(text) TO PUBLIC;

COMMENT ON FUNCTION public.encode_uri(text)
    IS 'Encoding for URL generated by Copilot. Prompt: with postgres - which function do you use to encode an Uri';


--#####################################################################################################################
--######   version   ##################################################################################################
--#####################################################################################################################

UPDATE "#project#"."Package" SET "Version" = 15 WHERE "Package" = 'ABCD'