--#####################################################################################################################
--#####################################################################################################################
--Skript for Update of Postgres package ABCD to version 13
--replace "#project#" with Name of the project
--the string at the begin of the line --## is used to mark end and begin of a command
--#####################################################################################################################
--#####################################################################################################################


--#####################################################################################################################
--######   Fixing the encode_uri function according to Copilot   ######################################################
--######   the previous version taken from https://stackoverflow.com/a/60260190 missed to encode the & sign   #########
--#####################################################################################################################

CREATE OR REPLACE FUNCTION public.encode_uri(
	text)
    RETURNS text
    LANGUAGE 'sql'
    COST 100
    IMMUTABLE STRICT PARALLEL UNSAFE
AS $BODY$

    select string_agg(
        case
            when bytes > 1 or c !~ '[0-9a-zA-Z_.-]+' then 
                regexp_replace(encode(convert_to(c, 'utf-8')::bytea, 'hex'), '(..)', E'%\\1', 'g')
            else 
                c
        end,
        ''
    )
    from (
        select c, octet_length(c) bytes
        from regexp_split_to_table($1, '') c
    ) q;
$BODY$;

ALTER FUNCTION public.encode_uri(text)
    OWNER TO "CacheAdmin";

GRANT EXECUTE ON FUNCTION public.encode_uri(text) TO "CacheAdmin";

GRANT EXECUTE ON FUNCTION public.encode_uri(text) TO PUBLIC;

COMMENT ON FUNCTION public.encode_uri(text)
    IS 'Encoding for URL generated by Copilot. Prompt: with postgres - which function do you use to encode an Uri';


--#####################################################################################################################
--######   version   ##################################################################################################
--#####################################################################################################################

UPDATE "#project#"."Package" SET "Version" = 13 WHERE "Package" = 'ABCD'