//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiversityCollection.CacheDatabase.Packages {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcePackages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcePackages() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiversityCollection.CacheDatabase.Packages.ResourcePackages", typeof(ResourcePackages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die --#####################################################################################################################
        ///--#####################################################################################################################
        ///--Skript for Update of Postgres package ABCD to version 2
        ///--replace &quot;#project#&quot; with Name of the project
        ///--the string at the begin of the line --## is used to mark end and begin of a command
        ///--########################################################################## [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ABCD_000001_to_000002 {
            get {
                return ResourceManager.GetString("ABCD_000001_to_000002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die --#####################################################################################################################
        ///--#####################################################################################################################
        ///--Skript for Update of Postgres package ABCD to version 3
        ///--replace &quot;#project#&quot; with Name of the project
        ///--the string at the begin of the line --## is used to mark end and begin of a command
        ///--########################################################################## [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ABCD_000002_to_000003 {
            get {
                return ResourceManager.GetString("ABCD_000002_to_000003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die --#####################################################################################################################
        ///--#####################################################################################################################
        ///--Skript for Update of Postgres package ABCD to version 4
        ///--replace &quot;#project#&quot; with Name of the project
        ///--the string at the begin of the line --## is used to mark end and begin of a command
        ///--########################################################################## [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ABCD_000003_to_000004 {
            get {
                return ResourceManager.GetString("ABCD_000003_to_000004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die --#####################################################################################################################
        ///--#####################################################################################################################
        ///--Skript for Update of Postgres package ABCD to version 5
        ///--replace &quot;#project#&quot; with Name of the project
        ///--the string at the begin of the line --## is used to mark end and begin of a command
        ///--########################################################################## [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ABCD_000004_to_000005 {
            get {
                return ResourceManager.GetString("ABCD_000004_to_000005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die --#####################################################################################################################
        ///--#####################################################################################################################
        ///--Skript for Update of Postgres package ABCD to version 6
        ///--replace &quot;#project#&quot; with Name of the project
        ///--the string at the begin of the line --## is used to mark end and begin of a command
        ///--########################################################################## [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ABCD_000005_to_000006 {
            get {
                return ResourceManager.GetString("ABCD_000005_to_000006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die --#####################################################################################################################
        ///--#####################################################################################################################
        ///--Skript for Update of Postgres package ABCD to version 7
        ///--replace &quot;#project#&quot; with Name of the project
        ///--the string at the begin of the line --## is used to mark end and begin of a command
        ///--########################################################################## [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ABCD_000006_to_000007 {
            get {
                return ResourceManager.GetString("ABCD_000006_to_000007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die --#####################################################################################################################
        ///--#####################################################################################################################
        ///--Skript for Update of Postgres package ABCD to version 8
        ///--replace &quot;#project#&quot; with Name of the project
        ///--the string at the begin of the line --## is used to mark end and begin of a command
        ///--########################################################################## [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ABCD_000007_to_000008 {
            get {
                return ResourceManager.GetString("ABCD_000007_to_000008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die --#####################################################################################################################
        ///--#####################################################################################################################
        ///--Skript for Update of Postgres package ABCD to version 8
        ///--replace &quot;#project#&quot; with Name of the project
        ///--the string at the begin of the line --## is used to mark end and begin of a command
        ///--########################################################################## [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ABCD_000008_to_000009 {
            get {
                return ResourceManager.GetString("ABCD_000008_to_000009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die --#####################################################################################################################
        ///--#####################################################################################################################
        ///--Skript for Update of Postgres package ABCD to version 10
        ///--replace &quot;#project#&quot; with Name of the project
        ///--the string at the begin of the line --## is used to mark end and begin of a command
        ///--######################################################################### [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ABCD_000009_to_000010 {
            get {
                return ResourceManager.GetString("ABCD_000009_to_000010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die --#####################################################################################################################
        ///--#####################################################################################################################
        ///--Skript for Update of Postgres package ABCD to version 11
        ///--replace &quot;#project#&quot; with Name of the project
        ///--the string at the begin of the line --## is used to mark end and begin of a command
        ///--######################################################################### [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ABCD_000010_to_000011 {
            get {
                return ResourceManager.GetString("ABCD_000010_to_000011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string ABCD_000011_to_000012 {
            get {
                return ResourceManager.GetString("ABCD_000011_to_000012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die --#####################################################################################################################
        ///--#####################################################################################################################
        ///--Skript for Update of Postgres package BayernFloraABCD to version 2
        ///--replace &quot;#project#&quot; with Name of the project
        ///--the string at the begin of the line --## is used to mark end and begin of a command
        ///--############################################################### [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ABCD_BayernFlora_000001_to_000002 {
            get {
                return ResourceManager.GetString("ABCD_BayernFlora_000001_to_000002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die --#####################################################################################################################
        ///--#####################################################################################################################
        ///--Skript for Update of Postgres package BayernFloraABCD to version 3
        ///--replace &quot;#project#&quot; with Name of the project
        ///--the string at the begin of the line --## is used to mark end and begin of a command
        ///--############################################################### [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ABCD_BayernFlora_000002_to_000003 {
            get {
                return ResourceManager.GetString("ABCD_BayernFlora_000002_to_000003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die --#####################################################################################################################
        ///--#####################################################################################################################
        ///--Skript for Update of Postgres package BayernFloraABCD to version 3
        ///--replace &quot;#project#&quot; with Name of the project
        ///--the string at the begin of the line --## is used to mark end and begin of a command
        ///--############################################################### [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ABCD_BayernFlora_000003_to_000004 {
            get {
                return ResourceManager.GetString("ABCD_BayernFlora_000003_to_000004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die --#####################################################################################################################
        ///--#####################################################################################################################
        ///--Skript for Update of Postgres package BayernFloraABCD to version 5
        ///--replace &quot;#project#&quot; with Name of the project
        ///--the string at the begin of the line --## is used to mark end and begin of a command
        ///--############################################################### [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ABCD_BayernFlora_000004_to_000005 {
            get {
                return ResourceManager.GetString("ABCD_BayernFlora_000004_to_000005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die --#####################################################################################################################
        ///--#####################################################################################################################
        ///--Skript for Update of Postgres package BayernFloraABCD to version 6
        ///--replace &quot;#project#&quot; with Name of the project
        ///--the string at the begin of the line --## is used to mark end and begin of a command
        ///--############################################################### [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ABCD_BayernFlora_000005_to_000006 {
            get {
                return ResourceManager.GetString("ABCD_BayernFlora_000005_to_000006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die -- FloraRaster
        ///
        ///--#####################################################################################################################
        ///--#####################################################################################################################
        ///--Skript for Update of Postgres package FloraRaster to version 2
        ///--replace &quot;#project#&quot; with Name of the project
        ///--the string at the begin of the line --## is used to mark end and begin of a command
        ///--################################################# [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string FloraRaster_000001_to_000002 {
            get {
                return ResourceManager.GetString("FloraRaster_000001_to_000002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die -- GUC
        ///
        ///--#####################################################################################################################
        ///--#####################################################################################################################
        ///--Skript for Update of Postgres package GUC to version 2
        ///--replace &quot;#project#&quot; with Name of the project
        ///--the string at the begin of the line --## is used to mark end and begin of a command
        ///--################################################################# [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string GUC_000001_to_000002 {
            get {
                return ResourceManager.GetString("GUC_000001_to_000002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die -- GUC
        ///
        ///--#####################################################################################################################
        ///--#####################################################################################################################
        ///--Skript for Update of Postgres package GUC to version 3
        ///--replace &quot;#project#&quot; with Name of the project
        ///--the string at the begin of the line --## is used to mark end and begin of a command
        ///--################################################################# [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string GUC_000002_to_000003 {
            get {
                return ResourceManager.GetString("GUC_000002_to_000003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die -- GUC
        ///
        ///--#####################################################################################################################
        ///--#####################################################################################################################
        ///--Skript for Update of Postgres package GUC to version 3
        ///--replace &quot;#project#&quot; with Name of the project
        ///--the string at the begin of the line --## is used to mark end and begin of a command
        ///--################################################################# [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string GUC_000003_to_000004 {
            get {
                return ResourceManager.GetString("GUC_000003_to_000004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die -- GUC
        ///
        ///--#####################################################################################################################
        ///--#####################################################################################################################
        ///--Skript for Update of Postgres package GUC to version 5
        ///--replace &quot;#project#&quot; with Name of the project
        ///--the string at the begin of the line --## is used to mark end and begin of a command
        ///--################################################################# [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string GUC_000004_to_000005 {
            get {
                return ResourceManager.GetString("GUC_000004_to_000005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die -- GUC
        ///
        ///--#####################################################################################################################
        ///--#####################################################################################################################
        ///--Skript for Update of Postgres package GUC to version 6
        ///--replace &quot;#project#&quot; with Name of the project
        ///--the string at the begin of the line --## is used to mark end and begin of a command
        ///--################################################################# [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string GUC_000005_to_000006 {
            get {
                return ResourceManager.GetString("GUC_000005_to_000006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die --#####################################################################################################################
        ///--#####################################################################################################################
        ///--Skript for Update of Postgres package LIDO to version 2
        ///--replace &quot;#project#&quot; with Name of the project
        ///--the string at the begin of the line --## is used to mark end and begin of a command
        ///--########################################################################## [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string LIDO_000001_to_000002 {
            get {
                return ResourceManager.GetString("LIDO_000001_to_000002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die -- Observation
        ///
        ///--#####################################################################################################################
        ///--#####################################################################################################################
        ///--Skript for Update of Postgres package Observation to version 2
        ///--replace &quot;#project#&quot; with Name of the project
        ///--the string at the begin of the line --## is used to mark end and begin of a command
        ///--################################################# [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Observation_000001_to_000002 {
            get {
                return ResourceManager.GetString("Observation_000001_to_000002", resourceCulture);
            }
        }
    }
}
