//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiversityCollection.Tasks {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection GrafanaDashboards {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["GrafanaDashboards"]));
            }
            set {
                this["GrafanaDashboards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int TopCollectionID {
            get {
                return ((int)(this["TopCollectionID"]));
            }
            set {
                this["TopCollectionID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ResponsibleAgent {
            get {
                return ((string)(this["ResponsibleAgent"]));
            }
            set {
                this["ResponsibleAgent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ResponsibleAgentURI {
            get {
                return ((string)(this["ResponsibleAgentURI"]));
            }
            set {
                this["ResponsibleAgentURI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection PrometheusApiLinks {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PrometheusApiLinks"]));
            }
            set {
                this["PrometheusApiLinks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[TNT.DIVERSITYWORKBENCH.DE,5432].DiversityTaxonNames_TaxaVaria")]
        public string DiversityTaxonNamesDatabase {
            get {
                return ((string)(this["DiversityTaxonNamesDatabase"]));
            }
            set {
                this["DiversityTaxonNamesDatabase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("380")]
        public int DiversityTaxonNamesProjectID {
            get {
                return ((int)(this["DiversityTaxonNamesProjectID"]));
            }
            set {
                this["DiversityTaxonNamesProjectID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection PestNameUris {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PestNameUris"]));
            }
            set {
                this["PestNameUris"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PrometheusServer {
            get {
                return ((string)(this["PrometheusServer"]));
            }
            set {
                this["PrometheusServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9090")]
        public int PrometheusPort {
            get {
                return ((int)(this["PrometheusPort"]));
            }
            set {
                this["PrometheusPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1192")]
        public int DiversityTaxonNamesBeneficialListID {
            get {
                return ((int)(this["DiversityTaxonNamesBeneficialListID"]));
            }
            set {
                this["DiversityTaxonNamesBeneficialListID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1190")]
        public int DiversityTaxonNamesPestListID {
            get {
                return ((int)(this["DiversityTaxonNamesPestListID"]));
            }
            set {
                this["DiversityTaxonNamesPestListID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection BeneficialNameUris {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BeneficialNameUris"]));
            }
            set {
                this["BeneficialNameUris"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1193")]
        public int DiversityTaxonNamesBycatchListID {
            get {
                return ((int)(this["DiversityTaxonNamesBycatchListID"]));
            }
            set {
                this["DiversityTaxonNamesBycatchListID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection BycatchNameUris {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BycatchNameUris"]));
            }
            set {
                this["BycatchNameUris"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowScientificName {
            get {
                return ((bool)(this["ShowScientificName"]));
            }
            set {
                this["ShowScientificName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncludeSpecimen {
            get {
                return ((bool)(this["IncludeSpecimen"]));
            }
            set {
                this["IncludeSpecimen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncludeCollections {
            get {
                return ((bool)(this["IncludeCollections"]));
            }
            set {
                this["IncludeCollections"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IncludeTransactions {
            get {
                return ((bool)(this["IncludeTransactions"]));
            }
            set {
                this["IncludeTransactions"] = value;
            }
        }
    }
}
