namespace DiversityCollection
{
    partial class Specimen
    {
        /// <summary>
        /// Erforderliche Designervariable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Verwendete Ressourcen bereinigen.
        /// </summary>
        /// <param name="disposing">True, wenn verwaltete Ressourcen gelöscht werden sollen; andernfalls False.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Vom Komponenten-Designer generierter Code

        /// <summary>
        /// Erforderliche Methode für die Designerunterstützung.
        /// Der Inhalt der Methode darf nicht mit dem Code-Editor geändert werden.
        /// </summary>
        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Specimen));
            imageList = new System.Windows.Forms.ImageList(components);
            imageListPart = new System.Windows.Forms.ImageList(components);
            imageListTaxonomicGroup = new System.Windows.Forms.ImageList(components);
            imageListMaterialCategory = new System.Windows.Forms.ImageList(components);
            dataSetCollectionEventSeries = new DiversityCollection.Datasets.DataSetCollectionEventSeries();
            dataSetCollectionSpecimen = new DiversityCollection.Datasets.DataSetCollectionSpecimen();
            imageListTablesAndFields = new System.Windows.Forms.ImageList(components);
            imageListUnitDescription = new System.Windows.Forms.ImageList(components);
            imageListUser = new System.Windows.Forms.ImageList(components);
            imageListLocalisationSystem = new System.Windows.Forms.ImageList(components);
            imageListTransaction = new System.Windows.Forms.ImageList(components);
            imageListRetrievalType = new System.Windows.Forms.ImageList(components);
            ((System.ComponentModel.ISupportInitialize)dataSetCollectionEventSeries).BeginInit();
            ((System.ComponentModel.ISupportInitialize)dataSetCollectionSpecimen).BeginInit();
            // 
            // imageList
            // 
            imageList.ColorDepth = System.Windows.Forms.ColorDepth.Depth24Bit;
            imageList.ImageStream = (System.Windows.Forms.ImageListStreamer)resources.GetObject("imageList.ImageStream");
            imageList.TransparentColor = System.Drawing.Color.Transparent;
            imageList.Images.SetKeyName(0, "NULL.ico");
            imageList.Images.SetKeyName(1, "EventSeriesHierarchy.ico");
            imageList.Images.SetKeyName(2, "EventSeriesHierarchyGrey.ico");
            imageList.Images.SetKeyName(3, "EventSeries.ico");
            imageList.Images.SetKeyName(4, "EventSeriesGrey.ico");
            imageList.Images.SetKeyName(5, "SamplingPlotHierarchy.ico");
            imageList.Images.SetKeyName(6, "SamplingPlotHierarchyGray.ico");
            imageList.Images.SetKeyName(7, "SamplingPlot.ico");
            imageList.Images.SetKeyName(8, "SamplingPlotGray.ico");
            imageList.Images.SetKeyName(9, "Event.ico");
            imageList.Images.SetKeyName(10, "EventGrey.ico");
            imageList.Images.SetKeyName(11, "Localisation.ico");
            imageList.Images.SetKeyName(12, "LocalisationGrey.ico");
            imageList.Images.SetKeyName(13, "EventProperty.ico");
            imageList.Images.SetKeyName(14, "EventPropertyGrey.ico");
            imageList.Images.SetKeyName(15, "CollectionSpecimen.ico");
            imageList.Images.SetKeyName(16, "CollectionSpecimenGrey.ico");
            imageList.Images.SetKeyName(17, "Collection.ico");
            imageList.Images.SetKeyName(18, "CollectionGrey.ico");
            imageList.Images.SetKeyName(19, "Identification.ico");
            imageList.Images.SetKeyName(20, "IdentificationGrey.ico");
            imageList.Images.SetKeyName(21, "Analysis.ico");
            imageList.Images.SetKeyName(22, "AnalysisGrey.ico");
            imageList.Images.SetKeyName(23, "AnalysisHierarchy.ico");
            imageList.Images.SetKeyName(24, "GeoAnalysis.ico");
            imageList.Images.SetKeyName(25, "GeoAnalysisGrey.ico");
            imageList.Images.SetKeyName(26, "Processing.ico");
            imageList.Images.SetKeyName(27, "ProcessingGrey.ico");
            imageList.Images.SetKeyName(28, "ProcessingHierarchy.ico");
            imageList.Images.SetKeyName(29, "TransactionOnLoan.ico");
            imageList.Images.SetKeyName(30, "TransactionOnLoanGrey.ico");
            imageList.Images.SetKeyName(31, "Transaction.ico");
            imageList.Images.SetKeyName(32, "TransactionGrey.ico");
            imageList.Images.SetKeyName(33, "Agent.ico");
            imageList.Images.SetKeyName(34, "AgentGrey.ico");
            imageList.Images.SetKeyName(35, "Relation.ico");
            imageList.Images.SetKeyName(36, "RelationGrey.ico");
            imageList.Images.SetKeyName(37, "RelationExtern.ico");
            imageList.Images.SetKeyName(38, "RelationInversGrey.ico");
            imageList.Images.SetKeyName(39, "Project.ico");
            imageList.Images.SetKeyName(40, "ProjectGrey.ico");
            imageList.Images.SetKeyName(41, "Specimen.ico");
            imageList.Images.SetKeyName(42, "SpecimenGrey.ico");
            imageList.Images.SetKeyName(43, "HerbariumSheet.ico");
            imageList.Images.SetKeyName(44, "HerbariumSheetGrey.ico");
            imageList.Images.SetKeyName(45, "Icones.ico");
            imageList.Images.SetKeyName(46, "IconesGrey.ico");
            imageList.Images.SetKeyName(47, "Drawing.ico");
            imageList.Images.SetKeyName(48, "DrawingGrey.ico");
            imageList.Images.SetKeyName(49, "Photography.ico");
            imageList.Images.SetKeyName(50, "PhotographyGrey.ico");
            imageList.Images.SetKeyName(51, "Dia.ico");
            imageList.Images.SetKeyName(52, "DiaGrey.ico");
            imageList.Images.SetKeyName(53, "Slide.ico");
            imageList.Images.SetKeyName(54, "MircoscopicSlideGrey.ico");
            imageList.Images.SetKeyName(55, "ThinSection.ico");
            imageList.Images.SetKeyName(56, "ThinSectionGrey.ico");
            imageList.Images.SetKeyName(57, "Culture.ico");
            imageList.Images.SetKeyName(58, "CultureGrey.ico");
            imageList.Images.SetKeyName(59, "Vial.ico");
            imageList.Images.SetKeyName(60, "VialGrey.ico");
            imageList.Images.SetKeyName(61, "SemTable.ico");
            imageList.Images.SetKeyName(62, "SemTableGrey.ico");
            imageList.Images.SetKeyName(63, "TEMgrid.ico");
            imageList.Images.SetKeyName(64, "TEMgridGrey.ico");
            imageList.Images.SetKeyName(65, "Bones.ico");
            imageList.Images.SetKeyName(66, "BonesGrey.ico");
            imageList.Images.SetKeyName(67, "Sceleton.ico");
            imageList.Images.SetKeyName(68, "SceletonGrey.ico");
            imageList.Images.SetKeyName(69, "Subcranial.ico");
            imageList.Images.SetKeyName(70, "SubcranialGrey.ico");
            imageList.Images.SetKeyName(71, "SkeletonIncomplete.ico");
            imageList.Images.SetKeyName(72, "SkeletonIncompleteGrey.ico");
            imageList.Images.SetKeyName(73, "Bone.ico");
            imageList.Images.SetKeyName(74, "BoneGrey.ico");
            imageList.Images.SetKeyName(75, "Zahn.ico");
            imageList.Images.SetKeyName(76, "ZahnGrey.ico");
            imageList.Images.SetKeyName(77, "Fell.ico");
            imageList.Images.SetKeyName(78, "FellGrey.ico");
            imageList.Images.SetKeyName(79, "DNA.ico");
            imageList.Images.SetKeyName(80, "DNAGrey.ico");
            imageList.Images.SetKeyName(81, "Observation.ico");
            imageList.Images.SetKeyName(82, "ObservationGrey.ico");
            imageList.Images.SetKeyName(83, "Fossil.ico");
            imageList.Images.SetKeyName(84, "FossilGrey.ico");
            imageList.Images.SetKeyName(85, "Media.ico");
            imageList.Images.SetKeyName(86, "MediaGrey.ico");
            imageList.Images.SetKeyName(87, "Trace.ico");
            imageList.Images.SetKeyName(88, "TraceGrey.ico");
            imageList.Images.SetKeyName(89, "Sound.ico");
            imageList.Images.SetKeyName(90, "SoundGrey.ico");
            imageList.Images.SetKeyName(91, "Otolith.ico");
            imageList.Images.SetKeyName(92, "OtolithGrey.ico");
            imageList.Images.SetKeyName(93, "Scales.ico");
            imageList.Images.SetKeyName(94, "ScalesGrey.ico");
            imageList.Images.SetKeyName(95, "Mould.ico");
            imageList.Images.SetKeyName(96, "MouldGrey.ico");
            imageList.Images.SetKeyName(97, "TissueSample.ico");
            imageList.Images.SetKeyName(98, "TissueSampleGray.ico");
            imageList.Images.SetKeyName(99, "Nest.ico");
            imageList.Images.SetKeyName(100, "NestGrey.ico");
            imageList.Images.SetKeyName(101, "Egg.ico");
            imageList.Images.SetKeyName(102, "EggGrey.ico");
            imageList.Images.SetKeyName(103, "Other.ICO");
            imageList.Images.SetKeyName(104, "Other_grau.ico");
            imageList.Images.SetKeyName(105, "Virus.ico");
            imageList.Images.SetKeyName(106, "VirusGrey.ico");
            imageList.Images.SetKeyName(107, "Bacterium.ico");
            imageList.Images.SetKeyName(108, "BacteriumGrey.ico");
            imageList.Images.SetKeyName(109, "Fungus.ico");
            imageList.Images.SetKeyName(110, "FungusGrey.ico");
            imageList.Images.SetKeyName(111, "Lichen.ico");
            imageList.Images.SetKeyName(112, "LichenGrey.ico");
            imageList.Images.SetKeyName(113, "Alga.ico");
            imageList.Images.SetKeyName(114, "AlgaGrey.ico");
            imageList.Images.SetKeyName(115, "Bryophyt.ico");
            imageList.Images.SetKeyName(116, "BryophytGrey.ico");
            imageList.Images.SetKeyName(117, "Plant.ico");
            imageList.Images.SetKeyName(118, "PlantGrey.ico");
            imageList.Images.SetKeyName(119, "Myxomycete.ico");
            imageList.Images.SetKeyName(120, "MyxomyceteGrey.ico");
            imageList.Images.SetKeyName(121, "Insect.ico");
            imageList.Images.SetKeyName(122, "InsectGrey.ico");
            imageList.Images.SetKeyName(123, "Mammal.ico");
            imageList.Images.SetKeyName(124, "MammalGrey.ico");
            imageList.Images.SetKeyName(125, "Mollusc.ico");
            imageList.Images.SetKeyName(126, "MolluscGrey.ico");
            imageList.Images.SetKeyName(127, "Bird.ico");
            imageList.Images.SetKeyName(128, "BirdGrey.ico");
            imageList.Images.SetKeyName(129, "Fish.ico");
            imageList.Images.SetKeyName(130, "FishGrey.ico");
            imageList.Images.SetKeyName(131, "Assel.ico");
            imageList.Images.SetKeyName(132, "AsselGrey.ico");
            imageList.Images.SetKeyName(133, "Echinoderm.ico");
            imageList.Images.SetKeyName(134, "EchinodermGrey.ico");
            imageList.Images.SetKeyName(135, "Vertebrata.ico");
            imageList.Images.SetKeyName(136, "VertebrataGrey.ico");
            imageList.Images.SetKeyName(137, "Reptile.ico");
            imageList.Images.SetKeyName(138, "ReptileGray.ico");
            imageList.Images.SetKeyName(139, "Evertebrate.ico");
            imageList.Images.SetKeyName(140, "EvertebrateGrey.ico");
            imageList.Images.SetKeyName(141, "Qualle.ico");
            imageList.Images.SetKeyName(142, "QualleGrey.ico");
            imageList.Images.SetKeyName(143, "Soil.ico");
            imageList.Images.SetKeyName(144, "SoilGrey.ico");
            imageList.Images.SetKeyName(145, "Raupe.ico");
            imageList.Images.SetKeyName(146, "RaupeGray.ico");
            imageList.Images.SetKeyName(147, "Animal.ico");
            imageList.Images.SetKeyName(148, "AnimalGray.ico");
            imageList.Images.SetKeyName(149, "Vertebrate.ico");
            imageList.Images.SetKeyName(150, "VertebrateGrey.ico");
            imageList.Images.SetKeyName(151, "Tree.ico");
            imageList.Images.SetKeyName(152, "TreeGrey.ico");
            imageList.Images.SetKeyName(153, "Zweig.ico");
            imageList.Images.SetKeyName(154, "ZweigGrey.ico");
            imageList.Images.SetKeyName(155, "Plant.ico");
            imageList.Images.SetKeyName(156, "PlantGrey.ico");
            imageList.Images.SetKeyName(157, "Root.ico");
            imageList.Images.SetKeyName(158, "RootGrey.ico");
            imageList.Images.SetKeyName(159, "Gall.ico");
            imageList.Images.SetKeyName(160, "GallGrey.ico");
            imageList.Images.SetKeyName(161, "Flower.ico");
            imageList.Images.SetKeyName(162, "FlowerGrey.ico");
            imageList.Images.SetKeyName(163, "LabelPrint.ico");
            imageList.Images.SetKeyName(164, "LabelPrintGrey.ico");
            imageList.Images.SetKeyName(165, "Note.ico");
            imageList.Images.SetKeyName(166, "NoteAdd.ico");
            imageList.Images.SetKeyName(167, "Ovaria.ico");
            imageList.Images.SetKeyName(168, "OvariaGrey.ico");
            imageList.Images.SetKeyName(169, "Altitude.ico");
            imageList.Images.SetKeyName(170, "AltitudeGrey.ico");
            imageList.Images.SetKeyName(171, "Depth.ico");
            imageList.Images.SetKeyName(172, "DepthGrey.ico");
            imageList.Images.SetKeyName(173, "Exposition.ico");
            imageList.Images.SetKeyName(174, "ExpositionGrey.ico");
            imageList.Images.SetKeyName(175, "GaussKrueger.ico");
            imageList.Images.SetKeyName(176, "GaussKruegerGrey.ico");
            imageList.Images.SetKeyName(177, "Height.ico");
            imageList.Images.SetKeyName(178, "HeightGrey.ico");
            imageList.Images.SetKeyName(179, "MTB.ico");
            imageList.Images.SetKeyName(180, "MTBGrey.ico");
            imageList.Images.SetKeyName(181, "Place.ico");
            imageList.Images.SetKeyName(182, "PlaceGrey.ico");
            imageList.Images.SetKeyName(183, "Slope.ico");
            imageList.Images.SetKeyName(184, "SlopeGrey.ico");
            imageList.Images.SetKeyName(185, "Geology.ico");
            imageList.Images.SetKeyName(186, "GeologyGrey.ico");
            imageList.Images.SetKeyName(187, "TransactionEmbargo.ico");
            imageList.Images.SetKeyName(188, "TransactionEmbargoGrey.ico");
            imageList.Images.SetKeyName(189, "RelationExtern.ico");
            imageList.Images.SetKeyName(190, "RelationExternGrey.ico");
            imageList.Images.SetKeyName(191, "Parent.ico");
            imageList.Images.SetKeyName(192, "ParentGrey.ico");
            imageList.Images.SetKeyName(193, "Tools.ico");
            imageList.Images.SetKeyName(194, "ToolsGrey.ico");
            imageList.Images.SetKeyName(195, "Parameter.ico");
            imageList.Images.SetKeyName(196, "ParameterGrey.ico");
            imageList.Images.SetKeyName(197, "Document.ICO");
            imageList.Images.SetKeyName(198, "DocumentGrex.ICO");
            imageList.Images.SetKeyName(199, "Hierarchy.ico");
            imageList.Images.SetKeyName(200, "HierarchyGrey.ico");
            imageList.Images.SetKeyName(201, "UnitInPart.ico");
            imageList.Images.SetKeyName(202, "UnitInPartGrey.ico");
            imageList.Images.SetKeyName(203, "TransactionForwarding.ico");
            imageList.Images.SetKeyName(204, "TransactionForwardingGrey.ico");
            imageList.Images.SetKeyName(205, "TransactionPermit.ico");
            imageList.Images.SetKeyName(206, "TransactionPermitGrey.ico");
            imageList.Images.SetKeyName(207, "TransactionReturn.ico");
            imageList.Images.SetKeyName(208, "TransactionReturnGrey.ico");
            imageList.Images.SetKeyName(209, "TransactionBorrow.ico");
            imageList.Images.SetKeyName(210, "TransactionBorrowGrey.ico");
            imageList.Images.SetKeyName(211, "TransactionGift.ico");
            imageList.Images.SetKeyName(212, "TransactionReturnGrey.ico");
            imageList.Images.SetKeyName(213, "TransactionRequest.ico");
            imageList.Images.SetKeyName(214, "TransactionRequestGrey.ico");
            imageList.Images.SetKeyName(215, "TransactionPurchase.ico");
            imageList.Images.SetKeyName(216, "TransactionReturnGrey.ico");
            imageList.Images.SetKeyName(217, "TransactionInventory.ico");
            imageList.Images.SetKeyName(218, "TransactionInventoryGrey.ico");
            imageList.Images.SetKeyName(219, "TransactionExchange.ico");
            imageList.Images.SetKeyName(220, "TransactionExchangeGrey.ico");
            imageList.Images.SetKeyName(221, "ImageArea.ico");
            imageList.Images.SetKeyName(222, "ImageAreaGrey.ico");
            imageList.Images.SetKeyName(223, "TransactionRemoval.ico");
            imageList.Images.SetKeyName(224, "TransactionRemovalGray.ico");
            imageList.Images.SetKeyName(225, "Archaea.ico");
            imageList.Images.SetKeyName(226, "ArchaeaGray.ico");
            imageList.Images.SetKeyName(227, "Chromista.ico");
            imageList.Images.SetKeyName(228, "ChromistaGray.ico");
            imageList.Images.SetKeyName(229, "Protozoa.ico");
            imageList.Images.SetKeyName(230, "ProtozoaGrey.ico");
            imageList.Images.SetKeyName(231, "Problem.ico");
            imageList.Images.SetKeyName(232, "ProblemGrey.ico");
            imageList.Images.SetKeyName(233, "References.ico");
            imageList.Images.SetKeyName(234, "ReferencesGray.ico");
            imageList.Images.SetKeyName(235, "Place_b.ico");
            imageList.Images.SetKeyName(236, "PlaceGrey.ico");
            imageList.Images.SetKeyName(237, "Place_c.ico");
            imageList.Images.SetKeyName(238, "PlaceGrey.ico");
            imageList.Images.SetKeyName(239, "Place_d.ico");
            imageList.Images.SetKeyName(240, "PlaceGrey.ico");
            imageList.Images.SetKeyName(241, "Place_e.ico");
            imageList.Images.SetKeyName(242, "PlaceGrey.ico");
            imageList.Images.SetKeyName(243, "Identifier.ico");
            imageList.Images.SetKeyName(244, "IdentifierGrey.ico");
            imageList.Images.SetKeyName(245, "Literature.ico");
            imageList.Images.SetKeyName(246, "LiteratureGray.ico");
            imageList.Images.SetKeyName(247, "Spider.ico");
            imageList.Images.SetKeyName(248, "SpiderGrey.ico");
            imageList.Images.SetKeyName(249, "Subcollection.ico");
            imageList.Images.SetKeyName(250, "SubcollectionGray.ico");
            imageList.Images.SetKeyName(251, "Payment.ico");
            imageList.Images.SetKeyName(252, "PaymentGray.ico");
            imageList.Images.SetKeyName(253, "Paragraph.ico");
            imageList.Images.SetKeyName(254, "ParagraphGrey.ico");
            imageList.Images.SetKeyName(255, "DNAlyo.ico");
            imageList.Images.SetKeyName(256, "DNAlyoGrey.ico");
            imageList.Images.SetKeyName(257, "PartDescription.ico");
            imageList.Images.SetKeyName(258, "PartDescriptionGray.ico");
            imageList.Images.SetKeyName(259, "Kristall.ico");
            imageList.Images.SetKeyName(260, "KristallGrey.ico");
            imageList.Images.SetKeyName(261, "Rock.ico");
            imageList.Images.SetKeyName(262, "RockGrey.ico");
            imageList.Images.SetKeyName(263, "Database.ico");
            imageList.Images.SetKeyName(264, "DatabaseGrey.ico");
            imageList.Images.SetKeyName(265, "Webservice.ico");
            imageList.Images.SetKeyName(266, "WebserviceGray.ico");
            imageList.Images.SetKeyName(267, "Human.ico");
            imageList.Images.SetKeyName(268, "HumanGray.ico");
            imageList.Images.SetKeyName(269, "Modell.ico");
            imageList.Images.SetKeyName(270, "ModellGray.ico");
            imageList.Images.SetKeyName(271, "Geology.ico");
            imageList.Images.SetKeyName(272, "GeologyGrey.ico");
            imageList.Images.SetKeyName(273, "MobileDevice.ico");
            imageList.Images.SetKeyName(274, "MobileDeviceGrey.ico");
            imageList.Images.SetKeyName(275, "Pin_3.ico");
            imageList.Images.SetKeyName(276, "Pin_3Gray.ico");
            imageList.Images.SetKeyName(277, "Settings.ico");
            imageList.Images.SetKeyName(278, "SettingsGrey.ico");
            imageList.Images.SetKeyName(279, "Box.ico");
            imageList.Images.SetKeyName(280, "BoxGrey.ico");
            imageList.Images.SetKeyName(281, "Cupboard.ico");
            imageList.Images.SetKeyName(282, "CupboardGrey.ico");
            imageList.Images.SetKeyName(283, "Drawer.ico");
            imageList.Images.SetKeyName(284, "DrawerGrey.ico");
            imageList.Images.SetKeyName(285, "Institution.ico");
            imageList.Images.SetKeyName(286, "InstitutionGrey.ico");
            imageList.Images.SetKeyName(287, "Radioaktiv.ico");
            imageList.Images.SetKeyName(288, "RadioaktivGrey.ico");
            imageList.Images.SetKeyName(289, "Room.ico");
            imageList.Images.SetKeyName(290, "RoomGrey.ico");
            imageList.Images.SetKeyName(291, "SteelLocker.ico");
            imageList.Images.SetKeyName(292, "SteelLockerGrey.ico");
            imageList.Images.SetKeyName(293, "Freezer.ico");
            imageList.Images.SetKeyName(294, "FreezerGrey.ico");
            imageList.Images.SetKeyName(295, "Fridge.ico");
            imageList.Images.SetKeyName(296, "FridgeGrey.ico");
            imageList.Images.SetKeyName(297, "Mineral.ico");
            imageList.Images.SetKeyName(298, "MineralGrey.ico");
            imageList.Images.SetKeyName(299, "Other2.ICO");
            imageList.Images.SetKeyName(300, "Other2Grey.ICO");
            imageList.Images.SetKeyName(301, "TableColumn.ico");
            imageList.Images.SetKeyName(302, "TableColumnGray.ico");
            imageList.Images.SetKeyName(303, "CacheDB.ico");
            imageList.Images.SetKeyName(304, "CacheDBGray.ico");
            imageList.Images.SetKeyName(305, "Workbench.ico");
            imageList.Images.SetKeyName(306, "DiversityWorkbenchGray.ico");
            imageList.Images.SetKeyName(307, "SoilHorizon.ico");
            imageList.Images.SetKeyName(308, "SoilHorizonGrey.ico");
            imageList.Images.SetKeyName(309, "IdentificationAdd.ico");
            imageList.Images.SetKeyName(310, "IdentificationAddGrey.ico");
            imageList.Images.SetKeyName(311, "Section.ico");
            imageList.Images.SetKeyName(312, "SectionGrey.ico");
            imageList.Images.SetKeyName(313, "Task.ico");
            imageList.Images.SetKeyName(314, "TaskGrey.ico");
            imageList.Images.SetKeyName(315, "Falle.ico");
            imageList.Images.SetKeyName(316, "FalleGrey.ico");
            imageList.Images.SetKeyName(317, "Gas.ico");
            imageList.Images.SetKeyName(318, "GasGrey.ico");
            imageList.Images.SetKeyName(319, "Poison.ico");
            imageList.Images.SetKeyName(320, "PoisonGrey.ico");
            imageList.Images.SetKeyName(321, "Radiation.ico");
            imageList.Images.SetKeyName(322, "RadiationGrey.ico");
            imageList.Images.SetKeyName(323, "IPM.ico");
            imageList.Images.SetKeyName(324, "IPMgrey.ico");
            imageList.Images.SetKeyName(325, "Kalender.ico");
            imageList.Images.SetKeyName(326, "KalenderGrey.ico");
            imageList.Images.SetKeyName(327, "Terminology.ico");
            imageList.Images.SetKeyName(328, "TerminologyGrey.ico");
            imageList.Images.SetKeyName(329, "Desc.ico");
            imageList.Images.SetKeyName(330, "DescGrey.ico");
            imageList.Images.SetKeyName(331, "DiversityAgents.ico");
            imageList.Images.SetKeyName(332, "DiversityAgentsGrey.ico");
            imageList.Images.SetKeyName(333, "DiversityCollection.ico");
            imageList.Images.SetKeyName(334, "DiversityCollectionGrey.ico");
            imageList.Images.SetKeyName(335, "DiversityGazetteer.ico");
            imageList.Images.SetKeyName(336, "DiversityGazetteerGrey.ico");
            imageList.Images.SetKeyName(337, "DiversityProjects.ico");
            imageList.Images.SetKeyName(338, "DiversityProjectsGrey.ico");
            imageList.Images.SetKeyName(339, "DiversityReferences.ico");
            imageList.Images.SetKeyName(340, "DiversityReferencesGrey.ico");
            imageList.Images.SetKeyName(341, "DiversitySamplingPlots.ico");
            imageList.Images.SetKeyName(342, "DiversitySamplingPlotsGrey.ico");
            imageList.Images.SetKeyName(343, "DiversityScientificTerms.ico");
            imageList.Images.SetKeyName(344, "DiversityScientificTermsGrey.ico");
            imageList.Images.SetKeyName(345, "DiversityTaxonNames.ico");
            imageList.Images.SetKeyName(346, "DiversityTaxonNamesGrey.ico");
            imageList.Images.SetKeyName(347, "Gazetteer.ico");
            imageList.Images.SetKeyName(348, "GazetteerGrey.ico");
            imageList.Images.SetKeyName(349, "Lupe.ico");
            imageList.Images.SetKeyName(350, "LupeGrey.ico");
            imageList.Images.SetKeyName(351, "DecisionRed.ico");
            imageList.Images.SetKeyName(352, "DecisionGrey.ico");
            imageList.Images.SetKeyName(353, "Graph.ico");
            imageList.Images.SetKeyName(354, "GraphGrey.ico");
            imageList.Images.SetKeyName(355, "Repair.ico");
            imageList.Images.SetKeyName(356, "RepairGrey.ico");
            imageList.Images.SetKeyName(357, "Schaden.ico");
            imageList.Images.SetKeyName(358, "SchadenGrey.ico");
            imageList.Images.SetKeyName(359, "Cleaning.ico");
            imageList.Images.SetKeyName(360, "CleaningGrey.ico");
            imageList.Images.SetKeyName(361, "CollectionTask.ico");
            imageList.Images.SetKeyName(362, "CollectionTaskGrey.ico");
            imageList.Images.SetKeyName(363, "Sensor.ico");
            imageList.Images.SetKeyName(364, "SensorGrey.ico");
            imageList.Images.SetKeyName(365, "Warning.ico");
            imageList.Images.SetKeyName(366, "WarningGray.ico");
            imageList.Images.SetKeyName(367, "SubdividedContainer.ico");
            imageList.Images.SetKeyName(368, "SubdividedContainerGray.ico");
            imageList.Images.SetKeyName(369, "FalleFang.ico");
            imageList.Images.SetKeyName(370, "FalleEnde.ico");
            imageList.Images.SetKeyName(371, "SensorHum.ico");
            imageList.Images.SetKeyName(372, "SensorHumGrey.ico");
            imageList.Images.SetKeyName(373, "SensorTemp.ico");
            imageList.Images.SetKeyName(374, "SensorTempGrey.ico");
            imageList.Images.SetKeyName(375, "Wetcollection.ico");
            imageList.Images.SetKeyName(376, "WetcollectionGrey.ico");
            imageList.Images.SetKeyName(377, "Container.ico");
            imageList.Images.SetKeyName(378, "ContainerGrey.ico");
            imageList.Images.SetKeyName(379, "Department.ico");
            imageList.Images.SetKeyName(380, "DepartmentGrey.ico");
            imageList.Images.SetKeyName(381, "Location.ico");
            imageList.Images.SetKeyName(382, "LocationGrey.ico");
            imageList.Images.SetKeyName(383, "Battery.ico");
            imageList.Images.SetKeyName(384, "BatteryGrey.ico");
            imageList.Images.SetKeyName(385, "Fliege.ico");
            imageList.Images.SetKeyName(386, "FliegeGrey.ico");
            imageList.Images.SetKeyName(387, "Monarch.ico");
            imageList.Images.SetKeyName(388, "MonarchGrey.ico");
            imageList.Images.SetKeyName(389, "Wanze.ico");
            imageList.Images.SetKeyName(390, "WanzeGrey.ico");
            imageList.Images.SetKeyName(391, "Wasp.ico");
            imageList.Images.SetKeyName(392, "WaspGrey.ico");
            imageList.Images.SetKeyName(393, "Coleoptera.ico");
            imageList.Images.SetKeyName(394, "ColeopteraGrey.ico");
            imageList.Images.SetKeyName(395, "Exhibition.ico");
            imageList.Images.SetKeyName(396, "ExhibitionGrey.ico");
            imageList.Images.SetKeyName(397, "Area.ico");
            imageList.Images.SetKeyName(398, "AreaGrey.ico");
            imageList.Images.SetKeyName(399, "Pinned.ico");
            imageList.Images.SetKeyName(400, "PinnedGrey.ico");
            imageList.Images.SetKeyName(401, "UTM.ico");
            imageList.Images.SetKeyName(402, "UTMgrey.ico");
            imageList.Images.SetKeyName(403, "Hardware.ico");
            imageList.Images.SetKeyName(404, "HardwareGrey.ico");
            imageList.Images.SetKeyName(405, "RelationInvers.ico");
            imageList.Images.SetKeyName(406, "RelationInversGrey.ico");
            imageList.Images.SetKeyName(407, "Rack.ico");
            imageList.Images.SetKeyName(408, "RackGrey.ico");
            imageList.Images.SetKeyName(409, "KeyBlue.ico");
            imageList.Images.SetKeyName(410, "KeyBlueGray.ico");
            imageList.Images.SetKeyName(411, "Organism.ico");
            imageList.Images.SetKeyName(412, "OrganismGrey.ico");
            imageList.Images.SetKeyName(413, "Bohrkern.ico");
            imageList.Images.SetKeyName(414, "BohrkernGrey.ico");
            // 
            // imageListPart
            // 
            imageListPart.ColorDepth = System.Windows.Forms.ColorDepth.Depth8Bit;
            imageListPart.ImageStream = (System.Windows.Forms.ImageListStreamer)resources.GetObject("imageListPart.ImageStream");
            imageListPart.TransparentColor = System.Drawing.Color.Transparent;
            imageListPart.Images.SetKeyName(0, "Tree.ico");
            imageListPart.Images.SetKeyName(1, "TreeGrey.ico");
            imageListPart.Images.SetKeyName(2, "Zweig.ico");
            imageListPart.Images.SetKeyName(3, "ZweigGrey.ico");
            imageListPart.Images.SetKeyName(4, "Plant.ico");
            imageListPart.Images.SetKeyName(5, "PlantGrey.ico");
            imageListPart.Images.SetKeyName(6, "Gall.ico");
            imageListPart.Images.SetKeyName(7, "GallGrey.ico");
            imageListPart.Images.SetKeyName(8, "Root.ico");
            imageListPart.Images.SetKeyName(9, "RootGrey.ico");
            imageListPart.Images.SetKeyName(10, "Sound.ico");
            imageListPart.Images.SetKeyName(11, "SoundGrey.ico");
            // 
            // imageListTaxonomicGroup
            // 
            imageListTaxonomicGroup.ColorDepth = System.Windows.Forms.ColorDepth.Depth8Bit;
            imageListTaxonomicGroup.ImageStream = (System.Windows.Forms.ImageListStreamer)resources.GetObject("imageListTaxonomicGroup.ImageStream");
            imageListTaxonomicGroup.TransparentColor = System.Drawing.Color.Transparent;
            imageListTaxonomicGroup.Images.SetKeyName(0, "NULL.ico");
            imageListTaxonomicGroup.Images.SetKeyName(1, "Other.ICO");
            imageListTaxonomicGroup.Images.SetKeyName(2, "Other_grau.ico");
            imageListTaxonomicGroup.Images.SetKeyName(3, "Virus.ico");
            imageListTaxonomicGroup.Images.SetKeyName(4, "VirusGrey.ico");
            imageListTaxonomicGroup.Images.SetKeyName(5, "Bacterium.ico");
            imageListTaxonomicGroup.Images.SetKeyName(6, "BacteriumGrey.ico");
            imageListTaxonomicGroup.Images.SetKeyName(7, "Fungus.ico");
            imageListTaxonomicGroup.Images.SetKeyName(8, "FungusGrey.ico");
            imageListTaxonomicGroup.Images.SetKeyName(9, "Lichen.ico");
            imageListTaxonomicGroup.Images.SetKeyName(10, "LichenGrey.ico");
            imageListTaxonomicGroup.Images.SetKeyName(11, "Alga.ico");
            imageListTaxonomicGroup.Images.SetKeyName(12, "AlgaGrey.ico");
            imageListTaxonomicGroup.Images.SetKeyName(13, "Bryophyt.ico");
            imageListTaxonomicGroup.Images.SetKeyName(14, "BryophytGrey.ico");
            imageListTaxonomicGroup.Images.SetKeyName(15, "Plant.ico");
            imageListTaxonomicGroup.Images.SetKeyName(16, "PlantGrey.ico");
            imageListTaxonomicGroup.Images.SetKeyName(17, "Myxomycete.ico");
            imageListTaxonomicGroup.Images.SetKeyName(18, "MyxomyceteGrey.ico");
            imageListTaxonomicGroup.Images.SetKeyName(19, "Insect.ico");
            imageListTaxonomicGroup.Images.SetKeyName(20, "InsectGrey.ico");
            imageListTaxonomicGroup.Images.SetKeyName(21, "Mammal.ico");
            imageListTaxonomicGroup.Images.SetKeyName(22, "MammalGrey.ico");
            imageListTaxonomicGroup.Images.SetKeyName(23, "Mollusc.ico");
            imageListTaxonomicGroup.Images.SetKeyName(24, "MolluscGrey.ico");
            imageListTaxonomicGroup.Images.SetKeyName(25, "Bird.ico");
            imageListTaxonomicGroup.Images.SetKeyName(26, "BirdGrey.ico");
            imageListTaxonomicGroup.Images.SetKeyName(27, "Fish.ico");
            imageListTaxonomicGroup.Images.SetKeyName(28, "FishGrey.ico");
            imageListTaxonomicGroup.Images.SetKeyName(29, "Assel.ico");
            imageListTaxonomicGroup.Images.SetKeyName(30, "AsselGrey.ico");
            imageListTaxonomicGroup.Images.SetKeyName(31, "Echinoderm.ico");
            imageListTaxonomicGroup.Images.SetKeyName(32, "EchinodermGrey.ico");
            imageListTaxonomicGroup.Images.SetKeyName(33, "Vertebrate.ico");
            imageListTaxonomicGroup.Images.SetKeyName(34, "VertebrateGrey.ico");
            imageListTaxonomicGroup.Images.SetKeyName(35, "Evertebrate.ico");
            imageListTaxonomicGroup.Images.SetKeyName(36, "EvertebrateGrey.ico");
            imageListTaxonomicGroup.Images.SetKeyName(37, "Qualle.ico");
            imageListTaxonomicGroup.Images.SetKeyName(38, "QualleGrey.ico");
            // 
            // imageListMaterialCategory
            // 
            imageListMaterialCategory.ColorDepth = System.Windows.Forms.ColorDepth.Depth8Bit;
            imageListMaterialCategory.ImageStream = (System.Windows.Forms.ImageListStreamer)resources.GetObject("imageListMaterialCategory.ImageStream");
            imageListMaterialCategory.TransparentColor = System.Drawing.Color.Transparent;
            imageListMaterialCategory.Images.SetKeyName(0, "NULL.ico");
            imageListMaterialCategory.Images.SetKeyName(1, "Specimen.ico");
            imageListMaterialCategory.Images.SetKeyName(2, "SpecimenGrey.ico");
            imageListMaterialCategory.Images.SetKeyName(3, "HerbariumSheet.ico");
            imageListMaterialCategory.Images.SetKeyName(4, "HerbariumSheetGrey.ico");
            imageListMaterialCategory.Images.SetKeyName(5, "Icones.ico");
            imageListMaterialCategory.Images.SetKeyName(6, "IconesGrey.ico");
            imageListMaterialCategory.Images.SetKeyName(7, "Drawing.ico");
            imageListMaterialCategory.Images.SetKeyName(8, "DrawingGrey.ico");
            imageListMaterialCategory.Images.SetKeyName(9, "Photography.ico");
            imageListMaterialCategory.Images.SetKeyName(10, "PhotographyGrey.ico");
            imageListMaterialCategory.Images.SetKeyName(11, "Dia.ico");
            imageListMaterialCategory.Images.SetKeyName(12, "DiaGrey.ico");
            imageListMaterialCategory.Images.SetKeyName(13, "Slide.ico");
            imageListMaterialCategory.Images.SetKeyName(14, "MircoscopicSlideGrey.ico");
            imageListMaterialCategory.Images.SetKeyName(15, "ThinSection.ico");
            imageListMaterialCategory.Images.SetKeyName(16, "ThinSectionGrey.ico");
            imageListMaterialCategory.Images.SetKeyName(17, "Culture.ico");
            imageListMaterialCategory.Images.SetKeyName(18, "CultureGrey.ico");
            imageListMaterialCategory.Images.SetKeyName(19, "Vial.ico");
            imageListMaterialCategory.Images.SetKeyName(20, "VialGrey.ico");
            imageListMaterialCategory.Images.SetKeyName(21, "SemTable.ico");
            imageListMaterialCategory.Images.SetKeyName(22, "SemTableGrey.ico");
            imageListMaterialCategory.Images.SetKeyName(23, "TEMgrid.ico");
            imageListMaterialCategory.Images.SetKeyName(24, "TEMgridGrey.ico");
            imageListMaterialCategory.Images.SetKeyName(25, "Bones.ico");
            imageListMaterialCategory.Images.SetKeyName(26, "BonesGrey.ico");
            imageListMaterialCategory.Images.SetKeyName(27, "Sceleton.ico");
            imageListMaterialCategory.Images.SetKeyName(28, "SceletonGrey.ico");
            imageListMaterialCategory.Images.SetKeyName(29, "Subcranial.ico");
            imageListMaterialCategory.Images.SetKeyName(30, "SubcranialGrey.ico");
            imageListMaterialCategory.Images.SetKeyName(31, "SkeletonIncomplete.ico");
            imageListMaterialCategory.Images.SetKeyName(32, "SkeletonIncompleteGrey.ico");
            imageListMaterialCategory.Images.SetKeyName(33, "Bone.ico");
            imageListMaterialCategory.Images.SetKeyName(34, "BoneGrey.ico");
            imageListMaterialCategory.Images.SetKeyName(35, "Zahn.ico");
            imageListMaterialCategory.Images.SetKeyName(36, "ZahnGrey.ico");
            imageListMaterialCategory.Images.SetKeyName(37, "Fell.ico");
            imageListMaterialCategory.Images.SetKeyName(38, "FellGrey.ico");
            imageListMaterialCategory.Images.SetKeyName(39, "DNA.ico");
            imageListMaterialCategory.Images.SetKeyName(40, "DNAGrey.ico");
            imageListMaterialCategory.Images.SetKeyName(41, "Observation.ico");
            imageListMaterialCategory.Images.SetKeyName(42, "ObservationGrey.ico");
            imageListMaterialCategory.Images.SetKeyName(43, "Fossil.ico");
            imageListMaterialCategory.Images.SetKeyName(44, "FossilGrey.ico");
            imageListMaterialCategory.Images.SetKeyName(45, "Media.ico");
            imageListMaterialCategory.Images.SetKeyName(46, "MediaGrey.ico");
            imageListMaterialCategory.Images.SetKeyName(47, "Trace.ico");
            imageListMaterialCategory.Images.SetKeyName(48, "TraceGrey.ico");
            imageListMaterialCategory.Images.SetKeyName(49, "Sound.ico");
            imageListMaterialCategory.Images.SetKeyName(50, "SoundGrey.ico");
            imageListMaterialCategory.Images.SetKeyName(51, "Otolith.ico");
            imageListMaterialCategory.Images.SetKeyName(52, "OtolithGrey.ico");
            // 
            // dataSetCollectionEventSeries
            // 
            dataSetCollectionEventSeries.DataSetName = "DataSetCollectionEventSeries";
            dataSetCollectionEventSeries.Namespace = "http://tempuri.org/DataSetCollectionEventSeries.xsd";
            dataSetCollectionEventSeries.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            // 
            // dataSetCollectionSpecimen
            // 
            dataSetCollectionSpecimen.DataSetName = "DataSetCollectionSpecimen";
            dataSetCollectionSpecimen.Namespace = "http://tempuri.org/DataSetCollectionSpecimen.xsd";
            dataSetCollectionSpecimen.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            // 
            // imageListTablesAndFields
            // 
            imageListTablesAndFields.ColorDepth = System.Windows.Forms.ColorDepth.Depth8Bit;
            imageListTablesAndFields.ImageStream = (System.Windows.Forms.ImageListStreamer)resources.GetObject("imageListTablesAndFields.ImageStream");
            imageListTablesAndFields.TransparentColor = System.Drawing.Color.Transparent;
            imageListTablesAndFields.Images.SetKeyName(0, "NULL.ico");
            imageListTablesAndFields.Images.SetKeyName(1, "EventSeries.ico");
            imageListTablesAndFields.Images.SetKeyName(2, "EventSeriesGrey.ico");
            imageListTablesAndFields.Images.SetKeyName(3, "Event.ico");
            imageListTablesAndFields.Images.SetKeyName(4, "EventGrey.ico");
            imageListTablesAndFields.Images.SetKeyName(5, "Time.ico");
            imageListTablesAndFields.Images.SetKeyName(6, "TimeGrey.ico");
            imageListTablesAndFields.Images.SetKeyName(7, "Localisation.ico");
            imageListTablesAndFields.Images.SetKeyName(8, "LocalisationGrey.ico");
            imageListTablesAndFields.Images.SetKeyName(9, "EventProperty.ico");
            imageListTablesAndFields.Images.SetKeyName(10, "EventPropertyGrey.ico");
            imageListTablesAndFields.Images.SetKeyName(11, "CollectionSpecimen.ico");
            imageListTablesAndFields.Images.SetKeyName(12, "CollectionSpecimenGrey.ico");
            imageListTablesAndFields.Images.SetKeyName(13, "Depositor.ico");
            imageListTablesAndFields.Images.SetKeyName(14, "DepositorGrey.ico");
            imageListTablesAndFields.Images.SetKeyName(15, "LabelPrint.ico");
            imageListTablesAndFields.Images.SetKeyName(16, "LabelPrintGrey.ico");
            imageListTablesAndFields.Images.SetKeyName(17, "Plant.ico");
            imageListTablesAndFields.Images.SetKeyName(18, "PlantGrey.ico");
            imageListTablesAndFields.Images.SetKeyName(19, "Identification.ico");
            imageListTablesAndFields.Images.SetKeyName(20, "IdentificationGrey.ico");
            imageListTablesAndFields.Images.SetKeyName(21, "Analysis.ico");
            imageListTablesAndFields.Images.SetKeyName(22, "AnalysisGrey.ico");
            imageListTablesAndFields.Images.SetKeyName(23, "Collection.ico");
            imageListTablesAndFields.Images.SetKeyName(24, "CollectionGrey.ico");
            imageListTablesAndFields.Images.SetKeyName(25, "Processing.ico");
            imageListTablesAndFields.Images.SetKeyName(26, "ProcessingGrey.ico");
            imageListTablesAndFields.Images.SetKeyName(27, "Transaction.ico");
            imageListTablesAndFields.Images.SetKeyName(28, "TransactionGrey.ico");
            imageListTablesAndFields.Images.SetKeyName(29, "Agent.ico");
            imageListTablesAndFields.Images.SetKeyName(30, "AgentGrey.ico");
            imageListTablesAndFields.Images.SetKeyName(31, "Relation.ico");
            imageListTablesAndFields.Images.SetKeyName(32, "RelationGrey.ico");
            imageListTablesAndFields.Images.SetKeyName(33, "Project.ico");
            imageListTablesAndFields.Images.SetKeyName(34, "ProjectGrey.ico");
            imageListTablesAndFields.Images.SetKeyName(35, "Icones.ico");
            imageListTablesAndFields.Images.SetKeyName(36, "IconesGrey.ico");
            imageListTablesAndFields.Images.SetKeyName(37, "Database.ico");
            imageListTablesAndFields.Images.SetKeyName(38, "DatabaseGrey.ico");
            imageListTablesAndFields.Images.SetKeyName(39, "Dictionary.ICO");
            imageListTablesAndFields.Images.SetKeyName(40, "DictionaryGrey.ico");
            imageListTablesAndFields.Images.SetKeyName(41, "References.ico");
            imageListTablesAndFields.Images.SetKeyName(42, "ReferencesGray.ico");
            imageListTablesAndFields.Images.SetKeyName(43, "TransactionEmbargo.ico");
            imageListTablesAndFields.Images.SetKeyName(44, "TransactionEmbargoGrey.ico");
            imageListTablesAndFields.Images.SetKeyName(45, "Tools.ico");
            imageListTablesAndFields.Images.SetKeyName(46, "ToolsGrey.ico");
            imageListTablesAndFields.Images.SetKeyName(47, "Parameter.ico");
            imageListTablesAndFields.Images.SetKeyName(48, "ParameterGrey.ico");
            imageListTablesAndFields.Images.SetKeyName(49, "Fingerprint.ico");
            imageListTablesAndFields.Images.SetKeyName(50, "FingerprintGray.ico");
            imageListTablesAndFields.Images.SetKeyName(51, "Document.ICO");
            imageListTablesAndFields.Images.SetKeyName(52, "DocumentGrex.ICO");
            imageListTablesAndFields.Images.SetKeyName(53, "Hierarchy.ico");
            imageListTablesAndFields.Images.SetKeyName(54, "HierarchyGrey.ico");
            imageListTablesAndFields.Images.SetKeyName(55, "Parent.ico");
            imageListTablesAndFields.Images.SetKeyName(56, "ParentGrey.ico");
            imageListTablesAndFields.Images.SetKeyName(57, "UnitInPart.ico");
            imageListTablesAndFields.Images.SetKeyName(58, "UnitInPartGrey.ico");
            imageListTablesAndFields.Images.SetKeyName(59, "ImageArea.ico");
            imageListTablesAndFields.Images.SetKeyName(60, "ImageAreaGrey.ico");
            // 
            // imageListUnitDescription
            // 
            imageListUnitDescription.ColorDepth = System.Windows.Forms.ColorDepth.Depth8Bit;
            imageListUnitDescription.ImageStream = (System.Windows.Forms.ImageListStreamer)resources.GetObject("imageListUnitDescription.ImageStream");
            imageListUnitDescription.TransparentColor = System.Drawing.Color.Transparent;
            imageListUnitDescription.Images.SetKeyName(0, "Tree.ico");
            imageListUnitDescription.Images.SetKeyName(1, "Zweig.ico");
            imageListUnitDescription.Images.SetKeyName(2, "Plant.ico");
            imageListUnitDescription.Images.SetKeyName(3, "Flower.ico");
            imageListUnitDescription.Images.SetKeyName(4, "Gall.ico");
            imageListUnitDescription.Images.SetKeyName(5, "Root.ico");
            // 
            // imageListUser
            // 
            imageListUser.ColorDepth = System.Windows.Forms.ColorDepth.Depth8Bit;
            imageListUser.ImageStream = (System.Windows.Forms.ImageListStreamer)resources.GetObject("imageListUser.ImageStream");
            imageListUser.TransparentColor = System.Drawing.Color.Transparent;
            imageListUser.Images.SetKeyName(0, "Agent.ico");
            imageListUser.Images.SetKeyName(1, "Manager.ico");
            imageListUser.Images.SetKeyName(2, "Requester.ico");
            imageListUser.Images.SetKeyName(3, "User.ico");
            imageListUser.Images.SetKeyName(4, "CollectionManager.ico");
            imageListUser.Images.SetKeyName(5, "Depositor.ico");
            // 
            // imageListLocalisationSystem
            // 
            imageListLocalisationSystem.ColorDepth = System.Windows.Forms.ColorDepth.Depth8Bit;
            imageListLocalisationSystem.ImageStream = (System.Windows.Forms.ImageListStreamer)resources.GetObject("imageListLocalisationSystem.ImageStream");
            imageListLocalisationSystem.TransparentColor = System.Drawing.Color.Transparent;
            imageListLocalisationSystem.Images.SetKeyName(0, "Localisation.ico");
            imageListLocalisationSystem.Images.SetKeyName(1, "Place.ico");
            imageListLocalisationSystem.Images.SetKeyName(2, "Altitude.ico");
            imageListLocalisationSystem.Images.SetKeyName(3, "Country.ico");
            imageListLocalisationSystem.Images.SetKeyName(4, "Depth.ico");
            imageListLocalisationSystem.Images.SetKeyName(5, "Exposition.ico");
            imageListLocalisationSystem.Images.SetKeyName(6, "GaussKrueger.ico");
            imageListLocalisationSystem.Images.SetKeyName(7, "Height.ico");
            imageListLocalisationSystem.Images.SetKeyName(8, "MTB.ico");
            imageListLocalisationSystem.Images.SetKeyName(9, "Slope.ico");
            imageListLocalisationSystem.Images.SetKeyName(10, "SamplingPlot.ico");
            imageListLocalisationSystem.Images.SetKeyName(11, "Place_b.ico");
            imageListLocalisationSystem.Images.SetKeyName(12, "Place_c.ico");
            imageListLocalisationSystem.Images.SetKeyName(13, "Place_d.ico");
            imageListLocalisationSystem.Images.SetKeyName(14, "Place_e.ico");
            imageListLocalisationSystem.Images.SetKeyName(15, "UTM.ico");
            // 
            // imageListTransaction
            // 
            imageListTransaction.ColorDepth = System.Windows.Forms.ColorDepth.Depth8Bit;
            imageListTransaction.ImageStream = (System.Windows.Forms.ImageListStreamer)resources.GetObject("imageListTransaction.ImageStream");
            imageListTransaction.TransparentColor = System.Drawing.Color.Transparent;
            imageListTransaction.Images.SetKeyName(0, "Transaction.ico");
            imageListTransaction.Images.SetKeyName(1, "TransactionGrey.ico");
            imageListTransaction.Images.SetKeyName(2, "TransactionEmbargo.ico");
            imageListTransaction.Images.SetKeyName(3, "TransactionEmbargoGrey.ico");
            imageListTransaction.Images.SetKeyName(4, "TransactionOnLoan.ico");
            imageListTransaction.Images.SetKeyName(5, "TransactionOnLoanGrey.ico");
            imageListTransaction.Images.SetKeyName(6, "TransactionExchange.ico");
            imageListTransaction.Images.SetKeyName(7, "TransactionInventory.ico");
            imageListTransaction.Images.SetKeyName(8, "TransactionRequest.ico");
            imageListTransaction.Images.SetKeyName(9, "TransactionForwarding.ico");
            imageListTransaction.Images.SetKeyName(10, "TransactionPermit.ico");
            imageListTransaction.Images.SetKeyName(11, "TransactionReturn.ico");
            imageListTransaction.Images.SetKeyName(12, "TransactionGift.ico");
            imageListTransaction.Images.SetKeyName(13, "TransactionBorrow.ico");
            imageListTransaction.Images.SetKeyName(14, "TransactionPurchase.ico");
            imageListTransaction.Images.SetKeyName(15, "TransactionGroup.ico");
            imageListTransaction.Images.SetKeyName(16, "TransactionRemoval.ico");
            imageListTransaction.Images.SetKeyName(17, "TransactionPermanentLoan.ico");
            imageListTransaction.Images.SetKeyName(18, "Paragraph.ico");
            imageListTransaction.Images.SetKeyName(19, "Warning.ico");
            imageListTransaction.Images.SetKeyName(20, "Task_16.ico");
            imageListTransaction.Images.SetKeyName(21, "IPM.ico");
            // 
            // imageListRetrievalType
            // 
            imageListRetrievalType.ColorDepth = System.Windows.Forms.ColorDepth.Depth24Bit;
            imageListRetrievalType.ImageStream = (System.Windows.Forms.ImageListStreamer)resources.GetObject("imageListRetrievalType.ImageStream");
            imageListRetrievalType.TransparentColor = System.Drawing.Color.Transparent;
            imageListRetrievalType.Images.SetKeyName(0, "Literature.ico");
            imageListRetrievalType.Images.SetKeyName(1, "Observation.ico");
            imageListRetrievalType.Images.SetKeyName(2, "Sound.ico");
            ((System.ComponentModel.ISupportInitialize)dataSetCollectionEventSeries).EndInit();
            ((System.ComponentModel.ISupportInitialize)dataSetCollectionSpecimen).EndInit();

        }

        #endregion

        private Datasets.DataSetCollectionSpecimen dataSetCollectionSpecimen;
        private Datasets.DataSetCollectionEventSeries dataSetCollectionEventSeries;
        public System.Windows.Forms.ImageList imageList;
        private System.Windows.Forms.ImageList imageListPart;
        public System.Windows.Forms.ImageList imageListTaxonomicGroup;
        public System.Windows.Forms.ImageList imageListMaterialCategory;
        public System.Windows.Forms.ImageList imageListTablesAndFields;
        public System.Windows.Forms.ImageList imageListUnitDescription;
        public System.Windows.Forms.ImageList imageListUser;
        public System.Windows.Forms.ImageList imageListLocalisationSystem;
        private System.Windows.Forms.ImageList imageListTransaction;
        private System.Windows.Forms.ImageList imageListRetrievalType;
    }
}
