//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiversityCollection.CacheDatabase {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class CacheDBsettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static CacheDBsettings defaultInstance = ((CacheDBsettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CacheDBsettings())));
        
        public static CacheDBsettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://biocase.snsb.info/wrapper/index.cgi")]
        public string BioCASEsources {
            get {
                return ((string)(this["BioCASEsources"]));
            }
            set {
                this["BioCASEsources"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int ChunkSizePostgres {
            get {
                return ((int)(this["ChunkSizePostgres"]));
            }
            set {
                this["ChunkSizePostgres"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100000")]
        public int ChunkLimitPostgres {
            get {
                return ((int)(this["ChunkLimitPostgres"]));
            }
            set {
                this["ChunkLimitPostgres"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100000")]
        public int ChunkSizeCacheDB {
            get {
                return ((int)(this["ChunkSizeCacheDB"]));
            }
            set {
                this["ChunkSizeCacheDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000000")]
        public int ChunkLimitCacheDB {
            get {
                return ((int)(this["ChunkLimitCacheDB"]));
            }
            set {
                this["ChunkLimitCacheDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TimeoutCacheDB {
            get {
                return ((int)(this["TimeoutCacheDB"]));
            }
            set {
                this["TimeoutCacheDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TimeoutPostgres {
            get {
                return ((int)(this["TimeoutPostgres"]));
            }
            set {
                this["TimeoutPostgres"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LogEvents {
            get {
                return ((bool)(this["LogEvents"]));
            }
            set {
                this["LogEvents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseChunksForPostgres {
            get {
                return ((bool)(this["UseChunksForPostgres"]));
            }
            set {
                this["UseChunksForPostgres"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StopOnError {
            get {
                return ((bool)(this["StopOnError"]));
            }
            set {
                this["StopOnError"] = value;
            }
        }
    }
}
