//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiversityCollection.Forms {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class FormReplicationSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static FormReplicationSettings defaultInstance = ((FormReplicationSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new FormReplicationSettings())));
        
        public static FormReplicationSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServerConnectionString {
            get {
                return ((string)(this["ServerConnectionString"]));
            }
            set {
                this["ServerConnectionString"] = value;
            }
        }
    }
}
