//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiversityCollection.Forms {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class FormIdentificationUnitGridModeSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static FormIdentificationUnitGridModeSettings defaultInstance = ((FormIdentificationUnitGridModeSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new FormIdentificationUnitGridModeSettings())));
        
        public static FormIdentificationUnitGridModeSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime AnalysisStartDate {
            get {
                return ((global::System.DateTime)(this["AnalysisStartDate"]));
            }
            set {
                this["AnalysisStartDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime AnalysisEndDate {
            get {
                return ((global::System.DateTime)(this["AnalysisEndDate"]));
            }
            set {
                this["AnalysisEndDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection AnalysisIDs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AnalysisIDs"]));
            }
            set {
                this["AnalysisIDs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseAnalysisStartDate {
            get {
                return ((bool)(this["UseAnalysisStartDate"]));
            }
            set {
                this["UseAnalysisStartDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseAnalysisEndDate {
            get {
                return ((bool)(this["UseAnalysisEndDate"]));
            }
            set {
                this["UseAnalysisEndDate"] = value;
            }
        }
    }
}
