//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiversityCollection.Forms {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class FormCollectionSpecimenSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static FormCollectionSpecimenSettings defaultInstance = ((FormCollectionSpecimenSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new FormCollectionSpecimenSettings())));
        
        public static FormCollectionSpecimenSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomSetting {
            get {
                return ((string)(this["CustomSetting"]));
            }
            set {
                this["CustomSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("333")]
        public int SplitContainerData_SplitterDistance {
            get {
                return ((int)(this["SplitContainerData_SplitterDistance"]));
            }
            set {
                this["SplitContainerData_SplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string QueryConditionVisibility {
            get {
                return ((string)(this["QueryConditionVisibility"]));
            }
            set {
                this["QueryConditionVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExportFields {
            get {
                return ((string)(this["ExportFields"]));
            }
            set {
                this["ExportFields"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TaxonomicGroups {
            get {
                return ((string)(this["TaxonomicGroups"]));
            }
            set {
                this["TaxonomicGroups"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MaterialCategories {
            get {
                return ((string)(this["MaterialCategories"]));
            }
            set {
                this["MaterialCategories"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0001")]
        public string ImageDisplay {
            get {
                return ((string)(this["ImageDisplay"]));
            }
            set {
                this["ImageDisplay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int QueryMaxResults {
            get {
                return ((int)(this["QueryMaxResults"]));
            }
            set {
                this["QueryMaxResults"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int DefaultCollection {
            get {
                return ((int)(this["DefaultCollection"]));
            }
            set {
                this["DefaultCollection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LocalisationSystems {
            get {
                return ((string)(this["LocalisationSystems"]));
            }
            set {
                this["LocalisationSystems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CollectionSiteProperties {
            get {
                return ((string)(this["CollectionSiteProperties"]));
            }
            set {
                this["CollectionSiteProperties"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GridModeVisibility {
            get {
                return ((string)(this["GridModeVisibility"]));
            }
            set {
                this["GridModeVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GridModeColumnWidth {
            get {
                return ((string)(this["GridModeColumnWidth"]));
            }
            set {
                this["GridModeColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GridModeColumnSequence {
            get {
                return ((string)(this["GridModeColumnSequence"]));
            }
            set {
                this["GridModeColumnSequence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultResponsible {
            get {
                return ((string)(this["DefaultResponsible"]));
            }
            set {
                this["DefaultResponsible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string DefaultResponsibleUsage {
            get {
                return ((string)(this["DefaultResponsibleUsage"]));
            }
            set {
                this["DefaultResponsibleUsage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultResponsibleURI {
            get {
                return ((string)(this["DefaultResponsibleURI"]));
            }
            set {
                this["DefaultResponsibleURI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GridModeUnitVisibility {
            get {
                return ((string)(this["GridModeUnitVisibility"]));
            }
            set {
                this["GridModeUnitVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GridModeUnitColumnWidth {
            get {
                return ((string)(this["GridModeUnitColumnWidth"]));
            }
            set {
                this["GridModeUnitColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GridModeUnitColumnSequence {
            get {
                return ((string)(this["GridModeUnitColumnSequence"]));
            }
            set {
                this["GridModeUnitColumnSequence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowExsiccata {
            get {
                return ((bool)(this["ShowExsiccata"]));
            }
            set {
                this["ShowExsiccata"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Taxa")]
        public string StorageLocationSource {
            get {
                return ((string)(this["StorageLocationSource"]));
            }
            set {
                this["StorageLocationSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection TransactionDisplaySequence {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TransactionDisplaySequence"]));
            }
            set {
                this["TransactionDisplaySequence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TransactionIncludeParentTitle {
            get {
                return ((bool)(this["TransactionIncludeParentTitle"]));
            }
            set {
                this["TransactionIncludeParentTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TransactionShowAllAddressFields {
            get {
                return ((bool)(this["TransactionShowAllAddressFields"]));
            }
            set {
                this["TransactionShowAllAddressFields"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TransactionIncludeDateInTitle {
            get {
                return ((bool)(this["TransactionIncludeDateInTitle"]));
            }
            set {
                this["TransactionIncludeDateInTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LocalisationSystemsInMaps {
            get {
                return ((string)(this["LocalisationSystemsInMaps"]));
            }
            set {
                this["LocalisationSystemsInMaps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Timeout {
            get {
                return ((int)(this["Timeout"]));
            }
            set {
                this["Timeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unknown")]
        public string StorageLocationText {
            get {
                return ((string)(this["StorageLocationText"]));
            }
            set {
                this["StorageLocationText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowAcceptedNames {
            get {
                return ((bool)(this["ShowAcceptedNames"]));
            }
            set {
                this["ShowAcceptedNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultResponsibleCurrent {
            get {
                return ((bool)(this["DefaultResponsibleCurrent"]));
            }
            set {
                this["DefaultResponsibleCurrent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScanDiversityDescriptons {
            get {
                return ((bool)(this["ScanDiversityDescriptons"]));
            }
            set {
                this["ScanDiversityDescriptons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection TargetHeights {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TargetHeights"]));
            }
            set {
                this["TargetHeights"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseCollectionLocation {
            get {
                return ((bool)(this["UseCollectionLocation"]));
            }
            set {
                this["UseCollectionLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection AutoCompleteExcludes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AutoCompleteExcludes"]));
            }
            set {
                this["AutoCompleteExcludes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SubcollectionContentMaxCount {
            get {
                return ((int)(this["SubcollectionContentMaxCount"]));
            }
            set {
                this["SubcollectionContentMaxCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowValidAgentName {
            get {
                return ((bool)(this["ShowValidAgentName"]));
            }
            set {
                this["ShowValidAgentName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>AccessionNumber</string>
  <string>Locality</string>
  <string>CollectionDate</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SubCollectionContentDisplayText {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SubCollectionContentDisplayText"]));
            }
            set {
                this["SubCollectionContentDisplayText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AskOnExit {
            get {
                return ((bool)(this["AskOnExit"]));
            }
            set {
                this["AskOnExit"] = value;
            }
        }
    }
}
