//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiversityCollection.Forms {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class FormTransactionSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static FormTransactionSettings defaultInstance = ((FormTransactionSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new FormTransactionSettings())));
        
        public static FormTransactionSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SendingSchemaFile {
            get {
                return ((string)(this["SendingSchemaFile"]));
            }
            set {
                this["SendingSchemaFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConfirmationSchemaFile {
            get {
                return ((string)(this["ConfirmationSchemaFile"]));
            }
            set {
                this["ConfirmationSchemaFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReminderSchemaFile {
            get {
                return ((string)(this["ReminderSchemaFile"]));
            }
            set {
                this["ReminderSchemaFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PartialReturnSchemaFile {
            get {
                return ((string)(this["PartialReturnSchemaFile"]));
            }
            set {
                this["PartialReturnSchemaFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReturnSchemaFile {
            get {
                return ((string)(this["ReturnSchemaFile"]));
            }
            set {
                this["ReturnSchemaFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int TimerIntervall {
            get {
                return ((int)(this["TimerIntervall"]));
            }
            set {
                this["TimerIntervall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BalanceSchemaFile {
            get {
                return ((string)(this["BalanceSchemaFile"]));
            }
            set {
                this["BalanceSchemaFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PrintingSchemaFile {
            get {
                return ((string)(this["PrintingSchemaFile"]));
            }
            set {
                this["PrintingSchemaFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RequestSchemaFile {
            get {
                return ((string)(this["RequestSchemaFile"]));
            }
            set {
                this["RequestSchemaFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ForwardingSchemaFile {
            get {
                return ((string)(this["ForwardingSchemaFile"]));
            }
            set {
                this["ForwardingSchemaFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowHierarchy {
            get {
                return ((bool)(this["ShowHierarchy"]));
            }
            set {
                this["ShowHierarchy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowSpecimenLists {
            get {
                return ((bool)(this["ShowSpecimenLists"]));
            }
            set {
                this["ShowSpecimenLists"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BalanceAdministrationAgentURI {
            get {
                return ((string)(this["BalanceAdministrationAgentURI"]));
            }
            set {
                this["BalanceAdministrationAgentURI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PdfInBrowserControl {
            get {
                return ((bool)(this["PdfInBrowserControl"]));
            }
            set {
                this["PdfInBrowserControl"] = value;
            }
        }
    }
}
