//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiversityCollection.Forms {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class FormLoanSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static FormLoanSettings defaultInstance = ((FormLoanSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new FormLoanSettings())));
        
        public static FormLoanSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SendingSchemaFile {
            get {
                return ((string)(this["SendingSchemaFile"]));
            }
            set {
                this["SendingSchemaFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConfirmationSchemaFile {
            get {
                return ((string)(this["ConfirmationSchemaFile"]));
            }
            set {
                this["ConfirmationSchemaFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReminderSchemaFile {
            get {
                return ((string)(this["ReminderSchemaFile"]));
            }
            set {
                this["ReminderSchemaFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PartialReturnSchemaFile {
            get {
                return ((string)(this["PartialReturnSchemaFile"]));
            }
            set {
                this["PartialReturnSchemaFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReturnSchemaFile {
            get {
                return ((string)(this["ReturnSchemaFile"]));
            }
            set {
                this["ReturnSchemaFile"] = value;
            }
        }
    }
}
