//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiversityCollection.Forms {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FormCollectionSpecimenText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormCollectionSpecimenText() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiversityCollection.Forms.FormCollectionSpecimenText", typeof(FormCollectionSpecimenText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All annotations ähnelt.
        /// </summary>
        internal static string All_annotations {
            get {
                return ResourceManager.GetString("All_annotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analysis ähnelt.
        /// </summary>
        internal static string Analysis {
            get {
                return ResourceManager.GetString("Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application_description ähnelt.
        /// </summary>
        internal static string Application_description {
            get {
                return ResourceManager.GetString("Application_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup database ähnelt.
        /// </summary>
        internal static string Backup_database {
            get {
                return ResourceManager.GetString("Backup_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cache database ähnelt.
        /// </summary>
        internal static string Cache_database {
            get {
                return ResourceManager.GetString("Cache_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change password ähnelt.
        /// </summary>
        internal static string Change_password {
            get {
                return ResourceManager.GetString("Change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Collection events ähnelt.
        /// </summary>
        internal static string Collection_events {
            get {
                return ResourceManager.GetString("Collection_events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Collection managers ähnelt.
        /// </summary>
        internal static string Collection_managers {
            get {
                return ResourceManager.GetString("Collection_managers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Collections ähnelt.
        /// </summary>
        internal static string Collections {
            get {
                return ResourceManager.GetString("Collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connection ähnelt.
        /// </summary>
        internal static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Context ähnelt.
        /// </summary>
        internal static string Context {
            get {
                return ResourceManager.GetString("Context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to create a new dataset? ähnelt.
        /// </summary>
        internal static string Create_new_dataset {
            get {
                return ResourceManager.GetString("Create_new_dataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Customize display ähnelt.
        /// </summary>
        internal static string Customize_display {
            get {
                return ResourceManager.GetString("Customize_display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data ähnelt.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database ähnelt.
        /// </summary>
        internal static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Depending data ähnelt.
        /// </summary>
        internal static string Depending_data {
            get {
                return ResourceManager.GetString("Depending_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display order for ähnelt.
        /// </summary>
        internal static string Display_order_for {
            get {
                return ResourceManager.GetString("Display_order_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit feedback ähnelt.
        /// </summary>
        internal static string Edit_feedback {
            get {
                return ResourceManager.GetString("Edit_feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Event series ähnelt.
        /// </summary>
        internal static string Event_series {
            get {
                return ResourceManager.GetString("Event_series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expired loans ähnelt.
        /// </summary>
        internal static string Expired_loans {
            get {
                return ResourceManager.GetString("Expired_loans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export list ähnelt.
        /// </summary>
        internal static string Export_list {
            get {
                return ResourceManager.GetString("Export_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die External datasources ähnelt.
        /// </summary>
        internal static string External_datasources {
            get {
                return ResourceManager.GetString("External_datasources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die External identifier ähnelt.
        /// </summary>
        internal static string External_identifier {
            get {
                return ResourceManager.GetString("External_identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die External relation to ähnelt.
        /// </summary>
        internal static string External_relation_to {
            get {
                return ResourceManager.GetString("External_relation_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feedback ähnelt.
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feedback history ähnelt.
        /// </summary>
        internal static string Feedback_history {
            get {
                return ResourceManager.GetString("Feedback_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grid ähnelt.
        /// </summary>
        internal static string Grid {
            get {
                return ResourceManager.GetString("Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image description ähnelt.
        /// </summary>
        internal static string Image_description {
            get {
                return ResourceManager.GetString("Image_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images ähnelt.
        /// </summary>
        internal static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import list ähnelt.
        /// </summary>
        internal static string Import_list {
            get {
                return ResourceManager.GetString("Import_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Internal relation to ähnelt.
        /// </summary>
        internal static string Internal_relation_to {
            get {
                return ResourceManager.GetString("Internal_relation_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kiosk mode ähnelt.
        /// </summary>
        internal static string Kiosk_mode {
            get {
                return ResourceManager.GetString("Kiosk_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Label print ähnelt.
        /// </summary>
        internal static string Label_print {
            get {
                return ResourceManager.GetString("Label_print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Linked server ähnelt.
        /// </summary>
        internal static string Linked_server {
            get {
                return ResourceManager.GetString("Linked_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loan requestors ähnelt.
        /// </summary>
        internal static string Loan_requestors {
            get {
                return ResourceManager.GetString("Loan_requestors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loan requests ähnelt.
        /// </summary>
        internal static string Loan_requests {
            get {
                return ResourceManager.GetString("Loan_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maintenance ähnelt.
        /// </summary>
        internal static string Maintenance {
            get {
                return ResourceManager.GetString("Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manual ähnelt.
        /// </summary>
        internal static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Material categories ähnelt.
        /// </summary>
        internal static string Material_categories {
            get {
                return ResourceManager.GetString("Material_categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Methods ähnelt.
        /// </summary>
        internal static string Methods {
            get {
                return ResourceManager.GetString("Methods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Module connections ähnelt.
        /// </summary>
        internal static string Module_connections {
            get {
                return ResourceManager.GetString("Module_connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die My requests ähnelt.
        /// </summary>
        internal static string My_requests {
            get {
                return ResourceManager.GetString("My_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No dataset could be found ähnelt.
        /// </summary>
        internal static string No_dataset_could_be_found {
            get {
                return ResourceManager.GetString("No_dataset_could_be_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die of ähnelt.
        /// </summary>
        internal static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Organisms ähnelt.
        /// </summary>
        internal static string Organisms {
            get {
                return ResourceManager.GetString("Organisms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parts ähnelt.
        /// </summary>
        internal static string Parts {
            get {
                return ResourceManager.GetString("Parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please delete all depending entries ähnelt.
        /// </summary>
        internal static string Please_delete_all_depending_entries {
            get {
                return ResourceManager.GetString("Please_delete_all_depending_entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select ähnelt.
        /// </summary>
        internal static string Please_select {
            get {
                return ResourceManager.GetString("Please_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Predefined queries ähnelt.
        /// </summary>
        internal static string Predefined_queries {
            get {
                return ResourceManager.GetString("Predefined_queries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Processing ähnelt.
        /// </summary>
        internal static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projects ähnelt.
        /// </summary>
        internal static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Queries ähnelt.
        /// </summary>
        internal static string Queries {
            get {
                return ResourceManager.GetString("Queries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Query ähnelt.
        /// </summary>
        internal static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quit ähnelt.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reimport list ähnelt.
        /// </summary>
        internal static string Reimport_list {
            get {
                return ResourceManager.GetString("Reimport_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove from project ähnelt.
        /// </summary>
        internal static string Remove_from_project {
            get {
                return ResourceManager.GetString("Remove_from_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove specimen ähnelt.
        /// </summary>
        internal static string Remove_specimen {
            get {
                return ResourceManager.GetString("Remove_specimen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replication ähnelt.
        /// </summary>
        internal static string Replication {
            get {
                return ResourceManager.GetString("Replication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resources directory ähnelt.
        /// </summary>
        internal static string Resources_directory {
            get {
                return ResourceManager.GetString("Resources_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restrict to collection ähnelt.
        /// </summary>
        internal static string Restrict_to_collection {
            get {
                return ResourceManager.GetString("Restrict_to_collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restrict to material ähnelt.
        /// </summary>
        internal static string Restrict_to_material {
            get {
                return ResourceManager.GetString("Restrict_to_material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Retrieval type ähnelt.
        /// </summary>
        internal static string Retrieval_type {
            get {
                return ResourceManager.GetString("Retrieval_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save dataset ähnelt.
        /// </summary>
        internal static string Save_dataset {
            get {
                return ResourceManager.GetString("Save_dataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scan mode ähnelt.
        /// </summary>
        internal static string Scan_mode {
            get {
                return ResourceManager.GetString("Scan_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scan mode collection ähnelt.
        /// </summary>
        internal static string Scan_mode_collection {
            get {
                return ResourceManager.GetString("Scan_mode_collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select a project ähnelt.
        /// </summary>
        internal static string Select_Project {
            get {
                return ResourceManager.GetString("Select_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show query ähnelt.
        /// </summary>
        internal static string Show_query {
            get {
                return ResourceManager.GetString("Show_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Site properties ähnelt.
        /// </summary>
        internal static string Site_properties {
            get {
                return ResourceManager.GetString("Site_properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Specimen scans ähnelt.
        /// </summary>
        internal static string Specimen_scans {
            get {
                return ResourceManager.GetString("Specimen_scans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Specimens ähnelt.
        /// </summary>
        internal static string Specimens {
            get {
                return ResourceManager.GetString("Specimens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Statistics ähnelt.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Table editor ähnelt.
        /// </summary>
        internal static string Table_editor {
            get {
                return ResourceManager.GetString("Table_editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Taxonomic groups ähnelt.
        /// </summary>
        internal static string Taxonomic_groups {
            get {
                return ResourceManager.GetString("Taxonomic_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There can only be one ähnelt.
        /// </summary>
        internal static string There_can_only_be_one {
            get {
                return ResourceManager.GetString("There_can_only_be_one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Timeout for database ähnelt.
        /// </summary>
        internal static string Timeout_for_database {
            get {
                return ResourceManager.GetString("Timeout_for_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To project ähnelt.
        /// </summary>
        internal static string To_project {
            get {
                return ResourceManager.GetString("To_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To transaction ähnelt.
        /// </summary>
        internal static string To_transaction {
            get {
                return ResourceManager.GetString("To_transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tools ähnelt.
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transaction ähnelt.
        /// </summary>
        internal static string Transaction {
            get {
                return ResourceManager.GetString("Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transaction management ähnelt.
        /// </summary>
        internal static string Transaction_management {
            get {
                return ResourceManager.GetString("Transaction_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transfer previous settings ähnelt.
        /// </summary>
        internal static string Transfer_previous_settings {
            get {
                return ResourceManager.GetString("Transfer_previous_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User and projects ähnelt.
        /// </summary>
        internal static string User_and_projects {
            get {
                return ResourceManager.GetString("User_and_projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Values are restricted to ähnelt.
        /// </summary>
        internal static string Values_are_restricted_to {
            get {
                return ResourceManager.GetString("Values_are_restricted_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Versions ähnelt.
        /// </summary>
        internal static string Versions {
            get {
                return ResourceManager.GetString("Versions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Withhold_data ähnelt.
        /// </summary>
        internal static string Withhold_data {
            get {
                return ResourceManager.GetString("Withhold_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wrong entry ähnelt.
        /// </summary>
        internal static string Wrong_entry {
            get {
                return ResourceManager.GetString("Wrong_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can not delete this entry here ähnelt.
        /// </summary>
        internal static string You_can_not_delete_this_entry_here {
            get {
                return ResourceManager.GetString("You_can_not_delete_this_entry_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have no access to this dataset ähnelt.
        /// </summary>
        internal static string You_have_no_access_to_this_dataset {
            get {
                return ResourceManager.GetString("You_have_no_access_to_this_dataset", resourceCulture);
            }
        }
    }
}
