//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.269
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiversityCollection.Forms {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class FormSynchronisationSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static FormSynchronisationSettings defaultInstance = ((FormSynchronisationSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new FormSynchronisationSettings())));
        
        public static FormSynchronisationSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SourceConnectionString {
            get {
                return ((string)(this["SourceConnectionString"]));
            }
            set {
                this["SourceConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SourceType {
            get {
                return ((string)(this["SourceType"]));
            }
            set {
                this["SourceType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DestinationConnectionString {
            get {
                return ((string)(this["DestinationConnectionString"]));
            }
            set {
                this["DestinationConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DestinationType {
            get {
                return ((string)(this["DestinationType"]));
            }
            set {
                this["DestinationType"] = value;
            }
        }
    }
}
