//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiversityCollection.Forms {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class FormPartGridSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static FormPartGridSettings defaultInstance = ((FormPartGridSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new FormPartGridSettings())));
        
        public static FormPartGridSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime AnalysisStartDate {
            get {
                return ((global::System.DateTime)(this["AnalysisStartDate"]));
            }
            set {
                this["AnalysisStartDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime AnalysisEndDate {
            get {
                return ((global::System.DateTime)(this["AnalysisEndDate"]));
            }
            set {
                this["AnalysisEndDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection AnalysisIDs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AnalysisIDs"]));
            }
            set {
                this["AnalysisIDs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime ProcessingStartDate {
            get {
                return ((global::System.DateTime)(this["ProcessingStartDate"]));
            }
            set {
                this["ProcessingStartDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime ProcessingEndDate {
            get {
                return ((global::System.DateTime)(this["ProcessingEndDate"]));
            }
            set {
                this["ProcessingEndDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ColumnWidth {
            get {
                return ((string)(this["ColumnWidth"]));
            }
            set {
                this["ColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ColumnSequence {
            get {
                return ((string)(this["ColumnSequence"]));
            }
            set {
                this["ColumnSequence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HeaderDisplay {
            get {
                return ((string)(this["HeaderDisplay"]));
            }
            set {
                this["HeaderDisplay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Visibility {
            get {
                return ((string)(this["Visibility"]));
            }
            set {
                this["Visibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ProcessingID {
            get {
                return ((int)(this["ProcessingID"]));
            }
            set {
                this["ProcessingID"] = value;
            }
        }
    }
}
