//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiversityCollection.Forms {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class FormCollectionSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static FormCollectionSettings defaultInstance = ((FormCollectionSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new FormCollectionSettings())));
        
        public static FormCollectionSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Show")]
        public string HierarchyDisplayState {
            get {
                return ((string)(this["HierarchyDisplayState"]));
            }
            set {
                this["HierarchyDisplayState"] = value;
            }
        }
    }
}
