//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiversityCollection.Forms {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class FormCollectionSpecimenGridModeSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static FormCollectionSpecimenGridModeSettings defaultInstance = ((FormCollectionSpecimenGridModeSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new FormCollectionSpecimenGridModeSettings())));
        
        public static FormCollectionSpecimenGridModeSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public string HeaderDisplay {
            get {
                return ((string)(this["HeaderDisplay"]));
            }
            set {
                this["HeaderDisplay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Autosuggest {
            get {
                return ((bool)(this["Autosuggest"]));
            }
            set {
                this["Autosuggest"] = value;
            }
        }
    }
}
